[profile.default]
src = "contracts"
out = "out-forge"
libs = ["node_modules", "lib"]
test = "test-forge"
remappings = ["@openzeppelin/=node_modules/@openzeppelin/", "forge-std/=lib/forge-std/src/"]
fs_permissions = []

[invariant]
runs = 64
depth = 32
fail_on_revert = false
